vich_uploader:
    db_driver: orm

    mappings:
        images_upload:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/private_assets/uploads/images'
            delete_on_update: false
            delete_on_remove: false
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        files_upload:
            uri_prefix: /uploads/files
            upload_destination: '%kernel.project_dir%/private_assets/uploads/files'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
